### ISSUE TITLE
GitHub Actions: Linux Build breaks when updating from 0.1.35 to 0.1.36 or 0.1.37-SNAPSHOT

### ISSUE THREAD

**Issue by taranion** [gluonhq/client-maven-plugin#296]
Hi,
I noticed that updating from client version 0.1.35 to 0.1.36 (or 0.1.37-SNAPSHOT) broke my ability to compile for Linux on GitHub actions, while building for Android still works perfectly.

The error is
**/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgtk-3.so: undefined reference to symbol 'g_module_symbol'**

I tried with ubuntu-18.04 and ubuntu-20.04. Downgrading to 0.1.35 also helps.
On my Fedora machine 0.1.37-SNAPSHOT works fine. It is only related to Github Actions.

```
[Sun Feb 07 22:11:34 UTC 2021][FINE] PB Command for link: gcc /home/runner/work/CommLink/CommLink/target/client/x86_64-linux/gvm/ComLink6/launcher.o /home/runner/work/CommLink/CommLink/target/client/x86_64-linux/gvm/tmp/SVM-1612735641758/de.rpgframework.shadowrun6.comlink.comlinkmain.o -Wl,-Bstatic -ljava -lnio -lzip -lnet -lprefs -ljvm -lj2pkcs11 -lsunec -lextnet -lfdlibm -llibchelper -Wl,-Bdynamic -lz -ldl -lstdc++ -lpthread -rdynamic -Wl,--whole-archive -lprism_es2 -lglass -lglassgtk3 -ljavafx_font -ljavafx_font_freetype -ljavafx_font_pango -ljavafx_iio -ljfxmedia -lfxplugins -lavplugin -ljfxwebkit -Wl,--no-whole-archive -lWebCore -lXMLJava -lJavaScriptCore -lbmalloc -licui18n -lSqliteJava -lXSLTJava -lPAL -lWebCoreTestSupport -lWTF -licuuc -licudata -Wl,--no-whole-archive -lGL -lX11 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lfreetype -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lgthread-2.0 -pthread -lglib-2.0 -lstdc++ -lz -lXtst -lm -lgmodule-2.0 -pthread -lglib-2.0 -lgstreamer-lite -lavcodec -lavformat -lavutil -lasound -o /home/runner/work/CommLink/CommLink/target/client/x86_64-linux/ComLink6 -L/home/runner/.gluon/substrate/javafxStaticSdk/16-ea+gvm31/linux-x86_64/sdk/lib -L/home/runner/work/_temp/_github_home/graalvm/lib/svm/clibraries/linux-amd64 -L/home/runner/work/_temp/_github_home/graalvm/lib/static/linux-amd64/glibc
[Sun Feb 07 22:11:34 UTC 2021][FINE] Start process link...
[Sun Feb 07 22:11:37 UTC 2021][INFO] [SUB] /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgtk-3.so: undefined reference to symbol 'g_module_symbol'
[Sun Feb 07 22:11:37 UTC 2021][INFO] [SUB] /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgmodule-2.0.so: error adding symbols: DSO missing from command line
[Sun Feb 07 22:11:37 UTC 2021][INFO] [SUB] collect2: error: ld returned 1 exit status
```

**Comment by alaa-abu-zidan** [comment]
I also have the same issue

**Comment by alaa-abu-zidan** [comment]
I found the issue in my case, awt library files are not being linked in my case, so if you are using java.desktop most likely you will get this error.

**Comment by jperedadnr** [comment]
Should be fixed with plugin 0.1.39
